# This is a basic workflow to help you get started with Actions

name: Close issues related to a merged pull request based on paw-dev branch.

# Controls when the action will run.
on:
  pull_request:
    types: [closed]
    branches:
      - paw-dev

jobs:
  closeIssueOnPrMergeTrigger:
    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
